development:
  adapter: mysql2
  database: ead_casserver
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8
test:
  adapter: mysql2
  database: ead_casserver
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8
production:
  adapter: mysql2
  database: ead_casserver
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8
